{{ config(materialized='table') }}

SELECT
    BNF_CHAPTER_CODE,
    BNF_CHAPTER,
    BNF_SECTION_CODE,
    BNF_SECTION,
    BNF_PARAGRAPH_CODE,
    BNF_PARAGRAPH,
    BNF_CHEMICAL_SUBSTANCE_CODE,
    BNF_CHEMICAL_SUBSTANCE,
    GENERIC_BNF_EQUIVALENT_NAME,
    BNF_PRESENTATION_NAME,
    SUM(CAST(NIC AS DOUBLE)) AS total_nic
FROM {{ ref('stg_prescription_costs_24_25') }}
GROUP BY
    BNF_CHAPTER_CODE, BNF_CHAPTER,
    BNF_SECTION_CODE, BNF_SECTION,
    BNF_PARAGRAPH_CODE, BNF_PARAGRAPH,
    BNF_CHEMICAL_SUBSTANCE_CODE, BNF_CHEMICAL_SUBSTANCE,
    GENERIC_BNF_EQUIVALENT_NAME,
    BNF_PRESENTATION_NAME
ORDER BY total_nic DESC
